### ISSUE TITLE
3.0 docs for pursuit

### ISSUE THREAD

**Issue by nwolverson** [purescript-node/purescript-node-os#3]
I tried to generate 3.0 docs for pursuit but I ran into this issue https://github.com/purescript/purescript/issues/3414/

**Comment by Thimoteus** [comment]
How are other people dealing with it? Desugaring it manually or waiting for a fix?

**Comment by hdgarrood** [comment]
Fix is due 24 Feb (assuming my PR gets merged); see https://github.com/purescript/purescript/pull/3514

**Comment by hdgarrood** [comment]
I suppose you could build from that branch and submit to Pursuit that way, too.

**Comment by JordanMartinez** [comment]
Closing as 4.0.0 has been released.
