### ISSUE TITLE
Transfer to `purescript-node` org

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-node/purescript-node-os#6]
Would you be up for transferring this repo to the `purescript-node` org?

**Comment by JordanMartinez** [comment]
This repo has been transferred. Now I need to update the Registry. @thomashoneyman can you help me out with this?

**Comment by thomashoneyman** [comment]
https://github.com/purescript/registry/issues/245

**Comment by JordanMartinez** [comment]
Thanks @thomashoneyman!
